version: '3'

services:
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.ch
      - PGADMIN_DEFAULT_PASSWORD=secret
    ports:
      - 5050:80
    networks:
      - aufgabenverwaltung
    volumes:
      - pgadmin-data:/root/.pgadmin
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=aufgabenverwaltung
    ports:
      - 5432:5432
    networks:
      - aufgabenverwaltung
    volumes:
      - postgres-db:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - aufgabenverwaltung
    volumes:
      - redis-data:/data

networks:
  aufgabenverwaltung:
    driver: bridge

volumes:
  postgres-db:
  pgadmin-data:
  redis-data: 